import sdk from '@stackblitz/sdk';
import { auth } from '@webcontainer/api';
import { v4 as uuidv4 } from 'uuid';

const CLIENT_ID = process.env.WEBCONTAINER_CLIENT_ID;

if (!CLIENT_ID) {
  console.error('❌ WEBCONTAINER_CLIENT_ID is not set in environment variables');
} else {
  try {
    auth.init({ clientId: CLIENT_ID, scope: '' });
    console.log('✅ WebContainer SDK initialized');
  } catch (error) {
    console.error('❌ WebContainer initialization failed:', error);
  }
}

export async function createStackBlitzPreview(
  html: string = '',
  css: string = '',
  js: string = '',
  files: Record<string, string> = {}
) {
  try {
    const projectId = `preview-${uuidv4().slice(0, 8)}`;

    // Cast project as 'any' to bypass type checking
    const project: any = {
      title: 'AI Live Preview',
      description: 'Generated by your AI builder',
      template: 'node',
      files: {
        'index.html': html || '<div id="root"></div>',
        'style.css': css || '',
        'index.js': js || 'console.log("Preview ready ✅");',
        'package.json': {
          content: JSON.stringify(
            {
              name: projectId,
              version: '1.0.0',
              scripts: { start: 'serve .' },
              dependencies: { serve: '^14.0.0' },
            },
            null,
            2
          ),
        },
        ...files,
      },
    };

    // Cast options as 'any' to prevent TypeScript from checking against 'Project' type
    const options: any = {
      embed: 1,
      hideExplorer: 1,
      hideNavigation: 1,
      view: 'preview',
      height: 600,
      openFile: 'index.js',
      terminalHeight: 0,
      devtoolsHeight: 0,
      forceEmbedLayout: true,
    };

    const embedUrl = sdk.embedProject(project, options);

    const embedHtml = `<iframe 
      src="${embedUrl}" 
      style="width:100%; height:600px; border:0; border-radius: 8px; background: white; box-shadow: 0 4px 12px rgba(0,0,0,0.1);"
      sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts allow-downloads allow-storage-access-by-user-activation"
      allow="accelerometer; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
      loading="lazy"
      title="AI Live Preview"
    ></iframe>`;

    return {
      success: true,
      previewUrl: embedUrl,
      embedHtml,
      projectId,
    };
  } catch (error) {
    console.error('❌ StackBlitz preview creation failed:', error);
    return {
      success: false,
      previewUrl: '',
      embedHtml: '',
      error: error instanceof Error ? error.message : String(error),
    };
  }
}