import sdk from '@stackblitz/sdk';
import { v4 as uuidv4 } from 'uuid';

export async function createStackBlitzPreview(
  html: string = '',
  css: string = '',
  js: string = '',
  files: Record<string, string> = {}
) {
  try {
    const projectId = `preview-${uuidv4().slice(0, 8)}`;

    // Build the project structure with an embedded error handler
    const project = {
      title: 'AI Live Preview',
      description: 'Generated by your AI builder',
      template: 'node',
      files: {
        // Main HTML – inject error handler script
        'index.html': (html || '<div id="root"></div>') + '\n<script src="error-handler.js"></script>',
        'style.css': css || '',
        'index.js': js || 'console.log("Preview ready ✅");',
        'package.json': JSON.stringify(
          {
            name: projectId,
            version: '1.0.0',
            scripts: { start: 'serve .' },
            dependencies: { serve: '^14.0.0' },
          },
          null,
          2
        ),
        // Error handler that captures all console output and errors
        'error-handler.js': `
          // Capture runtime errors
          window.addEventListener('error', function(event) {
            const errorData = {
              message: event.error?.message || event.message,
              stack: event.error?.stack || '',
              filename: event.filename,
              lineno: event.lineno,
              colno: event.colno,
              timestamp: Date.now()
            };
            window.parent.postMessage({ type: 'preview-error', error: errorData }, '*');
            return false;
          });

          // Capture unhandled promise rejections
          window.addEventListener('unhandledrejection', function(event) {
            window.parent.postMessage({
              type: 'preview-error',
              error: {
                message: event.reason?.message || 'Unhandled Promise Rejection',
                stack: event.reason?.stack || '',
                timestamp: Date.now()
              }
            }, '*');
          });

          // Capture console.log, warn, error, etc.
          const originalConsole = { ...console };
          ['log', 'warn', 'error', 'info', 'debug'].forEach(method => {
            console[method] = function(...args) {
              window.parent.postMessage({
                type: 'preview-console',
                method: method,
                args: args.map(arg => 
                  typeof arg === 'object' ? JSON.stringify(arg) : String(arg)
                ),
                timestamp: Date.now()
              }, '*');
              originalConsole[method].apply(console, args);
            };
          });
        `,
        // Include any additional files from the LLM
        ...files,
      },
    };

    // Generate the StackBlitz embed URL (no network call, synchronous)
    const embedUrl = sdk.embedProject(project, {
      embed: 1,
      hideExplorer: 1,
      hideNavigation: 1,
      view: 'preview',
      height: 600,
      openFile: 'index.js',
      terminalHeight: 0,
      devtoolsHeight: 0,
      forceEmbedLayout: true,
    });

    const embedHtml = `<iframe 
      src="${embedUrl}" 
      style="width:100%; height:600px; border:0; border-radius: 8px; background: white; box-shadow: 0 4px 12px rgba(0,0,0,0.1);"
      sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts allow-downloads allow-storage-access-by-user-activation"
      allow="accelerometer; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
      loading="lazy"
      title="AI Live Preview"
    ></iframe>`;

    return {
      success: true,
      previewUrl: embedUrl,
      embedHtml,
      projectId,
    };
  } catch (error) {
    console.error('❌ StackBlitz preview creation failed:', error);
    return {
      success: false,
      previewUrl: '',
      embedHtml: '',
      error: error instanceof Error ? error.message : String(error),
    };
  }
}
